version: '3'
volumes:
  db:
  gems:
services:
  db:
    image: postgres:9.6
  gems:
    image: busybox
    volumes:
      - /gems_cache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - gems
    links:
      - db
      - gems
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - gems:/gems_cache
    # Entrypoint for proper stopping: https://stackoverflow.com/a/38732187/1935918
    entrypoint: ["/app/lib/docker-entrypoint.sh"]
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    # command: ["sh"]
    # Keeps the stdin open, so we can attach to our app container's process and
    # do stuff such as `byebug` or `binding.pry`:
    stdin_open: true
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    environment:
      # Notice that this is the DB we'll use:
      # DATABASE_URL: postgres://postgres:s0m3p455@db:5432/my_app_development
      # We'll use this env variable to make the log output gets directed
      # to Docker:
      RAILS_LOG_TO_STDOUT: "true"
